// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6LcK7HA-ha4vMxsbYsWfhZaVkpkhmJWM',
    appId: '1:630626211648:web:1b550d90faf37e84574ca5',
    messagingSenderId: '630626211648',
    projectId: 'todo-5ebde',
    authDomain: 'todo-5ebde.firebaseapp.com',
    databaseURL: 'https://todo-5ebde-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todo-5ebde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1bq2Op9kot35oAsssP9D6TZx18CHt4c4',
    appId: '1:630626211648:android:92621085415b66de574ca5',
    messagingSenderId: '630626211648',
    projectId: 'todo-5ebde',
    databaseURL: 'https://todo-5ebde-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todo-5ebde.appspot.com',
  );
}
